(() => {
  "use strict";
  const S={data:null,af:"all",as:"",fs:"",ff:"all",es:null};
  const $=(q,r=document)=>r.querySelector(q), $$=(q,r=document)=>[...r.querySelectorAll(q)];
  const esc=v=>String(v??"").replaceAll("&","&amp;").replaceAll("<","&lt;").replaceAll(">","&gt;").replaceAll('"',"&quot;").replaceAll("'","&#039;");
  const n=v=>Number.isFinite(Number(v))?Number(v):0;
  const int=v=>v===null||v===undefined?"—":new Intl.NumberFormat("da-DK",{maximumFractionDigits:0}).format(n(v));
  const dkk=(v,d=2)=>new Intl.NumberFormat("da-DK",{minimumFractionDigits:d,maximumFractionDigits:d}).format(n(v));
  const pct=v=>`${Math.max(0,Math.min(100,Math.round(n(v))))}%`;
  const time=v=>v?new Intl.DateTimeFormat("da-DK",{hour:"2-digit",minute:"2-digit",second:"2-digit"}).format(new Date(Number(v)*1000)):"—";
  const dt=v=>v?new Intl.DateTimeFormat("da-DK",{day:"2-digit",month:"short",hour:"2-digit",minute:"2-digit"}).format(new Date(Number(v)*1000)):"—";
  const bytes=v=>{if(v==null)return"—";let x=Number(v),u=0,a=["B","KB","MB","GB","TB"];while(Math.abs(x)>=1024&&u<a.length-1){x/=1024;u++}return`${x.toLocaleString("da-DK",{maximumFractionDigits:u>1?1:0})} ${a[u]}`};
  const STATUS_LABELS={healthy:"Sund",attention:"Kræver kontrol",error:"Fejl",critical:"Kritisk",complete:"Klar",pending:"Analyseres",degraded:"Klar med forbehold",not_tracked:"Ikke overvåget",running:"Kører",online:"Online",available:"Tilgængelig",configured:"Konfigureret",active:"Aktiv",idle:"Ingen opgave",unknown:"Ukendt",detected:"Fundet",none:"Ingen",success:"Gennemført",stale:"Forældet",unavailable:"Utilgængelig"};
  const st=v=>STATUS_LABELS[String(v||"unknown").toLowerCase()]||String(v||"Ukendt").replaceAll("-"," ");
  const tone=v=>["healthy","attention","error","info","critical"].includes(v)?v:"info";
  const detail=(l,v)=>`<div class="detail-item"><span>${esc(l)}</span><strong>${esc(v??"—")}</strong></div>`;

  function conn(ok,text){$("#connectionDot").className=`pulse-dot ${ok?"online":"error"}`;$("#connectionLabel").textContent=ok?"Live forbindelse":"Forbindelse afbrudt";$("#connectionDetail").textContent=text||"Live status"}
  function err(msg){const e=$("#globalError");e.textContent=msg||"";e.classList.toggle("hidden",!msg)}
  function hero(d){const o=d.overall||{},s=o.status||"attention",orb=$("#overallOrb");orb.className=`status-orb ${s==="critical"?"critical":s==="healthy"?"healthy":"attention"}`;const m={healthy:["Systemet er grønt","Alle kritiske systemer er sunde","Kurv kører normalt. Ingen aktive driftsproblemer er registreret."],attention:["Kræver opmærksomhed","Kurv kører — noget kræver opmærksomhed","Kernesystemet er online, men der er kvalitets- eller driftsforhold nedenfor."],critical:["Kritisk status","Kurv har en kritisk driftsfejl","Mindst én central service kan ikke verificeres."]}[s]||[];$("#overallKicker").textContent=m[0];$("#overallTitle").textContent=m[1];$("#overallSubtitle").textContent=m[2];$("#releaseCommit").textContent=String(d.release?.commit||"unknown").slice(0,9);$("#releaseIos").textContent=`${d.release?.ios?.version||"—"} · build ${d.release?.ios?.build||"—"}`}
  function alerts(d){const a=d.alerts||[],t=$("#alertsList");$("#alertCount").textContent=a.length;if(!a.length){t.className="stack-list empty-state compact";t.textContent="Ingen aktive advarsler. Systemet har ikke noget, der kræver din opmærksomhed.";return}t.className="stack-list";t.innerHTML=a.map(x=>`<article class="alert-row ${esc(x.severity||"warning")}"><i class="alert-dot"></i><div><strong>${esc(x.title)}</strong>${x.detail?`<p>${esc(x.detail)}</p>`:""}</div></article>`).join("")}
  const RL={"core-api":"Core API","mobile-api":"Mobile API","luna-worker":"Luna worker","flyer-push-worker":"Flyer push","shopping-cleanup-worker":"Cleanup worker","samsung-login-broker":"Samsung login broker"};
  function runtime(d){const r=d.runtime||{},t=$("#runtimeGrid");t.className="runtime-list";t.innerHTML=Object.entries(RL).map(([id,label])=>{const x=r[id]||{},z=x.latency_ms!=null?`${int(x.latency_ms)} ms`:x.age_seconds!=null?`${int(x.age_seconds)} s siden`:st(x.state);return`<div class="runtime-row"><i class="state-dot ${tone(x.health)}"></i><span class="runtime-name">${esc(label)}</span><span class="runtime-detail">${esc(z)}</span></div>`}).join("")}
  function work(d){const l=d.runtime?.["luna-worker"]||{},p=d.runtime?.["flyer-push-worker"]||{},c=d.runtime?.["shopping-cleanup-worker"]||{},f=l.payload?.focus,cv=d.luna?.current_coverage||{};$("#currentWork").className="current-work-grid";$("#currentWork").innerHTML=`<article class="work-card"><span>Luna</span><strong>${esc(f?`${f.retailer} · ${f.title}`:"Ingen obligatorisk avis i kø")}</strong><p>${esc(f?`${f.pages_remaining??"?"} sider · ${f.pricing_remaining??"?"} pristjek · ${f.member_fallback_remaining??"?"} medlemspristjek tilbage`:`${cv.complete||0} klare · ${cv.degraded||0} klare med forbehold`)}</p></article><article class="work-card"><span>Avisovervågning</span><strong>${esc(p.detail||"Overvåger nye avisgenerationer")}</strong><p>${esc(p.payload?.last_provider_check_at?`Kilde senest kontrolleret ${time(p.payload.last_provider_check_at)} · ${p.payload.enabled_devices||0} aktive enheder`:"Afventer kildekontrol")}</p></article><article class="work-card"><span>Oprydning</span><strong>${esc(c.detail||"Planlagt oprydning")}</strong><p>${esc(c.payload?.next_run_in_hours!=null?`Næste kørsel om ${Number(c.payload.next_run_in_hours).toLocaleString("da-DK",{maximumFractionDigits:1})} timer`:"Afventer status")}</p></article>`}

  function archMatch(x){const f=S.af==="all"||x.layer===S.af||(S.af==="ios"&&x.runtime==="ios"),q=S.as.trim().toLowerCase();return f&&(!q||[x.name,x.layer,x.kind,x.runtime,x.code,x.description,...(x.depends_on||[])].join(" ").toLowerCase().includes(q))}
  function architecture(d){const a=(d.components||[]).filter(archMatch),g={};a.forEach(x=>(g[x.layer]??=[]).push(x));$("#architectureCount").textContent=`${a.length} komponenter`;$("#architectureLayers").innerHTML=a.length?Object.entries(g).map(([l,r])=>`<section class="layer-block"><h3>${esc(l)} · ${r.length}</h3><div class="component-grid">${r.map(x=>`<article class="component-card" tabindex="0" role="button" data-component="${esc(x.id)}"><div class="component-head"><span class="component-title">${esc(x.name)}</span><span class="health-pill ${tone(x.health)}">${esc(st(x.state))}</span></div><p>${esc(x.description)}</p><div class="component-meta"><span class="mini-tag">${esc(x.kind)}</span><span class="mini-tag">${esc(x.runtime)}</span><span class="mini-tag">${(x.depends_on||[]).length} afhængigheder</span></div></article>`).join("")}</div></section>`).join(""):`<div class="empty-state">Ingen komponenter matcher filtret.</div>`;bindComponents($("#architectureLayers"))}
  function flow(d){const c=Object.fromEntries((d.components||[]).map(x=>[x.id,x])),edges=d.dataflow||[],ids=["provider-tjek","flyer-adapters","flyer-readiness","luna-worker","luna-semantic-audit","luna-semantic-guards","member-coverage","flyer-serving","mobile-offers","smart-offer-matching","shopping-sync","samsung-food"];$("#dataflow").className="dataflow-strip";$("#dataflow").innerHTML=ids.filter(id=>c[id]).map((id,index)=>{const next=ids[index+1],edge=edges.find(e=>e.from===id&&e.to===next),label=edge?.label||c[id].layer;return`<div class="flow-node" data-component="${esc(id)}"><strong>${esc(c[id].name)}</strong><small>${esc(label)}</small></div>`}).join("");bindComponents($("#dataflow"))}
  function bindComponents(root){$$('[data-component]',root).forEach(e=>{const open=()=>componentDrawer(e.dataset.component);e.onclick=open;e.onkeydown=k=>{if(k.key==="Enter"||k.key===" "){k.preventDefault();open()}}})}

  function luna(d){const l=d.luna||{},u=l.usage||{},b=n(u.budget_dkk),s=n(u.estimated_cost_dkk),p=b?s/b*100:0,c=l.current_coverage||{},co=n(c.complete),pe=n(c.pending),de=n(c.degraded),nt=n(c.not_tracked),tot=co+pe+de+nt;$("#lunaModel").textContent=l.model||"Luna";$("#lunaSpent").textContent=dkk(s);$("#lunaBudget").textContent=`/ ${dkk(b,0)} kr.`;$("#lunaBudgetBar").style.width=pct(p);$("#lunaBudgetBar").style.background=p>=90?"var(--red)":p>=75?"var(--amber)":"var(--accent)";$("#lunaRequests").textContent=int(u.requests);$("#lunaTokens").textContent=int(n(u.input_tokens)+n(u.output_tokens));$("#lunaRemaining").textContent=dkk(u.remaining_dkk);$("#coverageComplete").textContent=co;$("#coveragePending").textContent=pe;$("#coverageDegraded").textContent=de;$("#coverageTotal").textContent=tot;const cp=tot?co/tot*100:0,pp=tot?pe/tot*100:0,dp=tot?de/tot*100:0;$("#coverageRing").style.background=`conic-gradient(var(--green) 0 ${cp}%,var(--amber) ${cp}% ${cp+pp}%,var(--orange) ${cp+pp}% ${cp+pp+dp}%,#dfe4e9 ${cp+pp+dp}% 100%)`;flyers(d)}
  function flyerMatch(x){const q=S.fs.trim().toLowerCase();return(S.ff==="all"||x.coverage_status===S.ff)&&(!q||`${x.retailer} ${x.title}`.toLowerCase().includes(q))}
  function flyers(d){const rows=(d.flyers?.publications||[]).filter(flyerMatch),t=$("#flyerTableBody");t.innerHTML=rows.length?rows.map(x=>`<tr data-publication="${esc(x.publication_id)}"><td><div class="flyer-name"><strong>${esc(x.retailer)}</strong><span>${esc(x.title)} · ${esc(x.valid_from||"—")}</span></div></td><td><span class="status-badge ${esc(x.coverage_status)}">${esc(st(x.coverage_status))}</span></td><td><div class="table-progress"><div class="progress-track"><span style="width:${pct(x.progress)};background:${x.coverage_status==="degraded"?"var(--orange)":x.coverage_status==="pending"?"var(--amber)":"var(--green)"}"></span></div><span>${pct(x.progress)}</span></div></td><td class="number-soft">${int(x.member_prices_verified)}</td><td class="${n(x.pricing_remaining)?"number-attention":"number-soft"}">${esc(x.pricing_remaining??"—")}</td><td class="${n(x.retry_candidates)?"number-attention":"number-soft"}">${int(x.retry_candidates)}</td><td class="${n(x.quarantine_count)?"number-warning":"number-soft"}">${int(x.quarantine_count)}</td></tr>`).join(""):`<tr><td colspan="7"><div class="empty-state">Ingen aviser matcher filtret.</div></td></tr>`;$$('[data-publication]',t).forEach(e=>e.onclick=()=>flyerDrawer(e.dataset.publication))}
  function integrations(d){const a=(d.components||[]).filter(x=>x.layer==="Integrationer");$("#integrationGrid").innerHTML=a.map(x=>`<article class="integration-card surface" data-component="${esc(x.id)}"><span class="health-pill ${tone(x.health)}">${esc(st(x.state))}</span><h3>${esc(x.name)}</h3><p>${esc(x.description)}</p><div class="integration-footer"><span class="code-label">${esc(x.code)}</span><span class="text-link">Detaljer →</span></div></article>`).join("");bindComponents($("#integrationGrid"))}
  function dataView(d){const x=d.data||{},h=x.households||{},m=x.offer_metadata||{},i=x.product_identity||{},c=x.category_overrides||{},v=x.volume||{};$("#dataCards").innerHTML=`<article class="data-stat-card surface"><span>Familiemedlemmer</span><strong>${int(h.members)}</strong><small>${int(h.households)} familier · ${int(h.pending_invites)} aktive invitationer</small></article><article class="data-stat-card surface"><span>Tilbudsdata</span><strong>${int(m.records)}</strong><small>${int(m.pinned)} fastgjorte · ${int(m.with_offer_snapshot)} øjebliksbilleder</small></article><article class="data-stat-card surface"><span>Vareidentitetslæring</span><strong>${int(i.stored_rules)}</strong><small>${int(c.records)} kategoriundtagelser · gemt cache</small></article><article class="data-stat-card surface"><span>QNAP-datavolumen</span><strong>${v.used_percent==null?"—":`${dkk(v.used_percent,1)}%`}</strong><small>${bytes(v.free_bytes)} ledig · ${bytes(v.used_bytes)} brugt</small></article>`;const r=h.records||[],t=$("#householdTable");t.className=r.length?"household-list":"household-list empty-state";t.innerHTML=r.length?r.map(y=>`<div class="household-row"><strong>${esc(y.name)}</strong><div class="household-cell"><span>Datalager</span>${esc(y.backend)}</div><div class="household-cell"><span>Medlemmer</span>${int(y.members)}</div><div class="household-cell"><span>Samsung</span>${esc(st(y.samsung_status))}</div><div class="household-cell"><span>Præferencer</span>${int(y.product_preferences)}</div><div class="household-cell"><span>Gendannelse</span>${y.recovery_configured?"Konfigureret":"Ikke sat"}</div></div>`).join(""):"Ingen familier registreret."}
  function timeline(d){const r=d.telemetry?.timeline||[];$("#timeline").innerHTML=r.length?r.map(x=>`<div class="timeline-row"><span class="timeline-time">${esc(dt(x.at))}</span><i class="timeline-dot"></i><div class="timeline-main"><strong>${esc(x.detail||x.type)}</strong><span>${esc(x.retailer||x.type)}</span></div><span class="timeline-status">${esc(st(x.status))}</span></div>`).join(""):`<div class="empty-state">Ingen aktivitet registreret endnu.</div>`}

  function render(d){S.data=d;err(null);hero(d);alerts(d);runtime(d);work(d);architecture(d);flow(d);luna(d);integrations(d);dataView(d);timeline(d);$("#lastUpdated").textContent=d.generated_at?`Opdateret ${time(d.generated_at)}`:"Live";window.dispatchEvent(new CustomEvent("kurv:snapshot",{detail:d}))}
  function drawer(o){$("#drawerEyebrow").textContent=o.eyebrow;$("#drawerTitle").textContent=o.title;$("#drawerContent").innerHTML=o.html;$("#drawerBackdrop").hidden=false;$("#detailDrawer").classList.add("open");$("#detailDrawer").setAttribute("aria-hidden","false")}
  function close(){$("#detailDrawer").classList.remove("open");$("#detailDrawer").setAttribute("aria-hidden","true");setTimeout(()=>$("#drawerBackdrop").hidden=true,220)}
  function componentDrawer(id){const x=S.data?.components?.find(y=>y.id===id);if(!x)return;const names=(x.depends_on||[]).map(z=>S.data.components.find(y=>y.id===z)?.name||z),rev=S.data.components.filter(y=>(y.depends_on||[]).includes(id)).map(y=>y.name);drawer({eyebrow:`${x.layer} · ${x.kind}`,title:x.name,html:`<section class="drawer-section"><div class="detail-grid">${detail("Status",st(x.state))}${detail("Health",x.health)}${detail("Lag",x.layer)}${detail("Runtime",x.runtime)}</div></section><section class="drawer-section"><h3>Ansvar</h3><p class="empty-state compact">${esc(x.description)}</p></section><section class="drawer-section"><h3>Kode</h3><div class="detail-item"><strong>${esc(x.code)}</strong></div></section><section class="drawer-section"><h3>Afhænger af</h3><div class="dependency-list">${names.length?names.map(z=>`<span class="dependency-pill">${esc(z)}</span>`).join(""):'<span class="empty-state compact">Ingen interne afhængigheder.</span>'}</div></section><section class="drawer-section"><h3>Bruges af</h3><div class="dependency-list">${rev.length?rev.map(z=>`<span class="dependency-pill">${esc(z)}</span>`).join(""):'<span class="empty-state compact">Ingen direkte downstream-komponenter.</span>'}</div></section>${x.detail?`<section class="drawer-section"><h3>Live note</h3><p class="empty-state compact">${esc(x.detail)}</p></section>`:""}`})}
  function flyerDrawer(id){const x=S.data?.flyers?.publications?.find(y=>y.publication_id===id);if(!x)return;const r=Object.entries(x.quarantine_reasons||{});drawer({eyebrow:`${x.retailer} · ${st(x.coverage_status)}`,title:x.title,html:`<section class="drawer-section"><div class="detail-grid">${detail("Coverage",st(x.coverage_status))}${detail("Source",st(x.source_status))}${detail("Sider",`${x.pages_done}/${x.pages_total}`)}${detail("Progress",pct(x.progress))}${detail("Medlemspriser verificeret",x.member_prices_verified)}${detail("Member fallbacks tilbage",x.member_fallback_remaining??"—")}${detail("Prischecks tilbage",x.pricing_remaining??"—")}${detail("Retry-kandidater",x.retry_candidates)}${detail("Quarantine",x.quarantine_count)}${detail("Luna records",x.luna_records)}</div></section><section class="drawer-section"><h3>Generation</h3><div class="detail-grid">${detail("Gyldig fra",x.valid_from||"—")}${detail("Gyldig til",x.valid_until||"—")}${detail("Fingerprint",x.fingerprint||"—")}${detail("Opdateret",dt(x.coverage_updated_at))}</div></section><section class="drawer-section"><h3>Quarantine-årsager</h3>${r.length?r.map(([z,k])=>`<div class="reason-row"><span>${esc(z)}</span><strong>${int(k)}</strong></div>`).join(""):'<div class="empty-state compact">Ingen quarantine-årsager på denne generation.</div>'}</section>${x.last_error?`<section class="drawer-section"><h3>Seneste source-fejl</h3><p class="empty-state compact">${esc(x.last_error)}</p></section>`:""}`})}

  async function fetchSnap(spin=false){if(spin)$("#manualRefresh").textContent="…";try{const r=await fetch("/api/snapshot",{cache:"no-store",headers:{Accept:"application/json"}});if(!r.ok)throw new Error(`HTTP ${r.status}`);render(await r.json());conn(true,"Live status")}catch(e){conn(false,"Snapshot utilgængeligt");err(`Kunne ikke hente Control Center-status: ${e.message}`)}finally{if(spin)$("#manualRefresh").textContent="↻"}}
  function sse(){if(S.es)S.es.close();const e=new EventSource("/api/events");S.es=e;e.addEventListener("snapshot",x=>{try{render(JSON.parse(x.data));conn(true,"Live · SSE")}catch(y){err(`Live snapshot kunne ikke læses: ${y.message}`)}});e.onopen=()=>conn(true,"Live · SSE");e.onerror=()=>{conn(false,"Genforbinder…");setTimeout(()=>{fetchSnap();if(S.es?.readyState===EventSource.CLOSED)sse()},2500)}}
  function nav(){const links=$$(".nav-item"),titles={overview:"Systemoverblik",architecture:"Arkitektur",luna:"Luna & tilbudsaviser",integrations:"Integrationer",data:"Data & familie",activity:"Aktivitet"},ob=new IntersectionObserver(es=>{const x=es.filter(e=>e.isIntersecting).sort((a,b)=>b.intersectionRatio-a.intersectionRatio)[0];if(!x)return;links.forEach(l=>l.classList.toggle("is-active",l.dataset.section===x.target.id));$("#pageTitle").textContent=titles[x.target.id]||"Kurv Control Center"},{rootMargin:"-20% 0px -60% 0px",threshold:[0,.15,.4]});$$(".section-anchor").forEach(x=>ob.observe(x))}
  function events(){$("#manualRefresh").onclick=()=>fetchSnap(true);$("#drawerClose").onclick=close;$("#drawerBackdrop").onclick=close;document.addEventListener("keydown",e=>{if(e.key==="Escape")close()});$("#architectureSearch").oninput=e=>{S.as=e.target.value;if(S.data)architecture(S.data)};$$('#architectureFilters .segment').forEach(b=>b.onclick=()=>{$$('#architectureFilters .segment').forEach(x=>x.classList.remove("is-active"));b.classList.add("is-active");S.af=b.dataset.filter;if(S.data)architecture(S.data)});$("#flyerSearch").oninput=e=>{S.fs=e.target.value;if(S.data)flyers(S.data)};$("#flyerStatusFilter").onchange=e=>{S.ff=e.target.value;if(S.data)flyers(S.data)}}
  document.addEventListener("DOMContentLoaded",async()=>{events();await fetchSnap();sse()});
})();
