from __future__ import annotations

from typing import Any


# The Control Center catalog is deliberately explicit. It is the human-readable
# architecture contract for Kurv, not a directory listing. A component belongs
# here when it has an operational or product responsibility that matters when
# diagnosing the system end-to-end.
COMPONENTS: tuple[dict[str, Any], ...] = (
    {
        "id": "core-api",
        "name": "Kurv Core API",
        "layer": "Runtime",
        "kind": "service",
        "runtime": "qnap",
        "code": "backend/app/main.py",
        "description": "Privat kerne-API og Samsung Food/Family Hub-list connector.",
        "depends_on": ["samsung-food", "samsung-auth"],
    },
    {
        "id": "mobile-api",
        "name": "Kurv Mobile API",
        "layer": "Runtime",
        "kind": "service",
        "runtime": "qnap",
        "code": "backend/app/mobile_main.py",
        "description": "Autentificeret gateway mellem iOS, familiedata, tilbud, aviser og integrationslag.",
        "depends_on": ["core-api", "household-engine", "mobile-offers", "offer-metadata"],
    },
    {
        "id": "control-center",
        "name": "Kurv Control Center",
        "layer": "Runtime",
        "kind": "service",
        "runtime": "qnap-local",
        "code": "backend/app/control_center.py",
        "description": "Read-only lokal observability, arkitekturkort, live-status og diagnosticering.",
        "depends_on": ["core-api", "mobile-api", "luna-worker", "flyer-push-worker"],
    },
    {
        "id": "luna-worker",
        "name": "Luna Coverage Worker",
        "layer": "Runtime",
        "kind": "worker",
        "runtime": "qnap",
        "code": "backend/app/luna_resilient_strong_worker.py",
        "description": "Coverage-first, bounded-retry Luna worker med non-blocking avis-release.",
        "depends_on": ["openai-luna", "flyer-readiness", "luna-semantic-audit", "member-coverage"],
    },
    {
        "id": "flyer-push-worker",
        "name": "Flyer Push Worker",
        "layer": "Runtime",
        "kind": "worker",
        "runtime": "qnap",
        "code": "backend/app/flyer_push_quality.py",
        "description": "Finder nye avis-generationer og sender først APNs efter afsluttet member-price coverage.",
        "depends_on": ["flyer-readiness", "member-coverage", "apple-apns"],
    },
    {
        "id": "shopping-cleanup-worker",
        "name": "Shopping Cleanup Worker",
        "layer": "Runtime",
        "kind": "worker",
        "runtime": "qnap",
        "code": "backend/app/shopping_cleanup.py",
        "description": "Fjerner købte varer ved midnat og rydder tilknyttet tilbudsmetadata sikkert.",
        "depends_on": ["samsung-food", "offer-metadata", "household-engine"],
    },
    {
        "id": "samsung-login-broker",
        "name": "Samsung Login Broker",
        "layer": "Runtime",
        "kind": "service",
        "runtime": "qnap",
        "code": "backend/app/login_broker.py",
        "description": "Isoleret browser/login-broker for interaktiv Samsung Food-godkendelse.",
        "depends_on": ["samsung-auth", "mobile-api"],
    },
    {
        "id": "samsung-food",
        "name": "Samsung Food / Family Hub",
        "layer": "Integrationer",
        "kind": "integration",
        "runtime": "external",
        "code": "backend/app/samsung.py",
        "description": "Fælles indkøbsliste som synkroniseres med Samsung Food og køleskabet via gRPC-web.",
        "depends_on": ["samsung-auth", "grpc-web"],
    },
    {
        "id": "samsung-auth",
        "name": "Samsung Auth Manager",
        "layer": "Integrationer",
        "kind": "integration",
        "runtime": "qnap+external",
        "code": "backend/app/auth.py",
        "description": "Persistente Samsung credentials, token-validering og sikker refresh uden at nulstille integrationen.",
        "depends_on": [],
    },
    {
        "id": "grpc-web",
        "name": "Samsung gRPC-Web Bridge",
        "layer": "Integrationer",
        "kind": "protocol",
        "runtime": "qnap+external",
        "code": "backend/app/grpc_web.py",
        "description": "Transportlaget for Samsung Food-listens read/write-operationer.",
        "depends_on": ["samsung-auth"],
    },
    {
        "id": "provider-tjek",
        "name": "Tjek / eTilbudsavis Provider",
        "layer": "Integrationer",
        "kind": "integration",
        "runtime": "external",
        "code": "backend/app/flyer_adapters.py",
        "description": "Kilde til kataloger, sider, hotspots og strukturerede tilbud for de understøttede butikker.",
        "depends_on": [],
    },
    {
        "id": "openai-luna",
        "name": "OpenAI Luna",
        "layer": "Integrationer",
        "kind": "ai-integration",
        "runtime": "external",
        "code": "backend/app/luna_enrichment.py",
        "description": "Visuel AI-verifikation af produktidentitet, prisroller, medlemstilbud og varianter.",
        "depends_on": [],
    },
    {
        "id": "apple-apns",
        "name": "Apple Push Notifications",
        "layer": "Integrationer",
        "kind": "integration",
        "runtime": "external",
        "code": "backend/app/flyer_push.py",
        "description": "Push af nye kvalitetssikrede tilbudsaviser til familiens iPhones.",
        "depends_on": ["flyer-push-worker"],
    },
    {
        "id": "household-engine",
        "name": "Family & Household Engine",
        "layer": "Kerne",
        "kind": "engine",
        "runtime": "mobile-api",
        "code": "backend/app/households.py",
        "description": "Familier, medlemmer, roller, invites, recovery og valg af liste-backend.",
        "depends_on": ["mobile-api"],
    },
    {
        "id": "shopping-sync",
        "name": "Shopping List Sync Engine",
        "layer": "Kerne",
        "kind": "engine",
        "runtime": "core+mobile",
        "code": "backend/app/main.py + backend/app/mobile_main.py",
        "description": "Read/write af fælles indkøbsliste med Samsung eller lokal familie-backend.",
        "depends_on": ["household-engine", "samsung-food"],
    },
    {
        "id": "offer-metadata",
        "name": "Shared Offer Metadata",
        "layer": "Kerne",
        "kind": "engine",
        "runtime": "mobile-api",
        "code": "backend/app/mobile_offer_metadata.py",
        "description": "Familiedelt binding mellem listevarer og valgte tilbud, butik, pris og gyldighed.",
        "depends_on": ["household-engine", "mobile-api"],
    },
    {
        "id": "mobile-offers",
        "name": "Offers & Publications API",
        "layer": "Avispipeline",
        "kind": "engine",
        "runtime": "mobile-api",
        "code": "backend/app/mobile_offers.py",
        "description": "Servering, søgning og normalisering af aktuelle tilbud og tilbudsaviser til iOS.",
        "depends_on": ["flyer-serving", "member-pricing", "product-identity"],
    },
    {
        "id": "flyer-adapters",
        "name": "Flyer Adapter Layer",
        "layer": "Avispipeline",
        "kind": "engine",
        "runtime": "mobile+luna",
        "code": "backend/app/flyer_adapters.py",
        "description": "Normaliserer retailer/provider-data til Kurvs fælles Publication/Offer-model.",
        "depends_on": ["provider-tjek"],
    },
    {
        "id": "flyer-readiness",
        "name": "Flyer Readiness Engine",
        "layer": "Avispipeline",
        "kind": "engine",
        "runtime": "shared-data",
        "code": "backend/app/flyer_readiness.py",
        "description": "Fingerprint-baseret generationsstyring, source-readiness og changed-page tracking.",
        "depends_on": ["flyer-adapters"],
    },
    {
        "id": "flyer-serving",
        "name": "Stable Flyer Serving Cache",
        "layer": "Avispipeline",
        "kind": "engine",
        "runtime": "mobile-api",
        "code": "backend/app/luna_overlay.py + backend/app/flyer_serving_reader.py",
        "description": "Serverer stabile snapshots og anvender kun verificeret Luna-enrichment oven på provider-baseline.",
        "depends_on": ["flyer-readiness", "luna-pricing-reader"],
    },
    {
        "id": "flyer-intelligence",
        "name": "Flyer Intelligence Engine",
        "layer": "Avispipeline",
        "kind": "engine",
        "runtime": "backend",
        "code": "backend/app/flyer_intelligence.py",
        "description": "Deterministisk tekst-, variant- og kvalitetsintelligens før/ved siden af Luna.",
        "depends_on": ["flyer-adapters", "variant-engine"],
    },
    {
        "id": "member-pricing",
        "name": "Member Pricing Engine v4",
        "layer": "Prisintelligens",
        "kind": "engine",
        "runtime": "backend",
        "code": "backend/app/member_pricing_v4.py + backend/app/member_pricing.py",
        "description": "Generisk medlemsprisdetektion på tværs af butikker; ordinary price forbliver primær.",
        "depends_on": ["luna-pricing-reader", "luna-semantic-guards"],
    },
    {
        "id": "luna-semantic-audit",
        "name": "Luna Semantic Page Audit",
        "layer": "Prisintelligens",
        "kind": "ai-engine",
        "runtime": "luna-worker",
        "code": "backend/app/luna_semantic_audit.py",
        "description": "High-detail sideaudit der returnerer én struktureret observation for hvert target offer.",
        "depends_on": ["openai-luna", "flyer-adapters"],
    },
    {
        "id": "luna-semantic-guards",
        "name": "Luna Semantic Safety Guards",
        "layer": "Prisintelligens",
        "kind": "safety-engine",
        "runtime": "luna+mobile",
        "code": "backend/app/luna_semantic_guards.py",
        "description": "Fail-closed prisrolle-, unit-price- og medlemstilbudsregler der forhindrer usikre AI-overrides.",
        "depends_on": ["luna-semantic-audit"],
    },
    {
        "id": "luna-pricing-reader",
        "name": "Luna Pricing Reader & Overlay",
        "layer": "Prisintelligens",
        "kind": "engine",
        "runtime": "mobile-api",
        "code": "backend/app/luna_pricing_reader.py + backend/app/luna_overlay.py",
        "description": "Read-only projektion af verificerede Luna-facts til customer-facing tilbud uden nye AI-kald.",
        "depends_on": ["luna-semantic-guards", "openai-luna"],
    },
    {
        "id": "member-coverage",
        "name": "Full Flyer Member Coverage",
        "layer": "Prisintelligens",
        "kind": "quality-engine",
        "runtime": "luna-worker",
        "code": "backend/app/luna_member_coverage.py",
        "description": "Persistent complete/degraded/pending quality-state pr. avis-generation før push-notifikation.",
        "depends_on": ["luna-semantic-audit", "luna-semantic-guards", "luna-worker"],
    },
    {
        "id": "luna-cost-policy",
        "name": "Luna Quality & Cost Policy",
        "layer": "Prisintelligens",
        "kind": "policy-engine",
        "runtime": "luna-worker",
        "code": "backend/app/luna_cost_policy.py",
        "description": "Prioriterer pris/member-sikkerhed, targeted crops og optional variant-spend under hard budget.",
        "depends_on": ["openai-luna", "luna-semantic-guards"],
    },
    {
        "id": "product-identity",
        "name": "Product Identity Engine",
        "layer": "Vareintelligens",
        "kind": "engine",
        "runtime": "mobile-api",
        "code": "backend/app/product_identity.py",
        "description": "Canonical vareidentitet, størrelse/enhed, familiepræferencer og konservativ matchklassifikation.",
        "depends_on": ["variant-engine", "household-engine"],
    },
    {
        "id": "variant-engine",
        "name": "Variant Extraction Engine v3",
        "layer": "Vareintelligens",
        "kind": "engine",
        "runtime": "backend",
        "code": "backend/app/variant_extractor_v3.py",
        "description": "Udtrækker og adskiller konkrete produktvarianter uden at blande forskellige varer/pakninger.",
        "depends_on": ["flyer-intelligence"],
    },
    {
        "id": "smart-offer-matching",
        "name": "Smart Offer Matching",
        "layer": "iOS Intelligence",
        "kind": "client-engine",
        "runtime": "ios",
        "code": "ios/BaggerShopping/SmartOfferMatching.swift",
        "description": "Matcher listevarer mod relevante tilbud med sikker identity/variant-logik.",
        "depends_on": ["product-identity", "mobile-offers", "offer-price-guard"],
    },
    {
        "id": "offer-price-guard",
        "name": "Offer Price Guard",
        "layer": "iOS Intelligence",
        "kind": "client-safety",
        "runtime": "ios",
        "code": "ios/BaggerShopping/Services/OfferPriceGuard.swift",
        "description": "Klientside sikkerhed mod forkerte pris-/pakningssammenligninger.",
        "depends_on": ["product-identity", "member-pricing"],
    },
    {
        "id": "offer-search-ranker",
        "name": "Offer Search Ranker",
        "layer": "iOS Intelligence",
        "kind": "client-engine",
        "runtime": "ios",
        "code": "ios/BaggerShopping/Services/OfferSearchRanker.swift",
        "description": "Rangerer tilbudssøgning efter relevans og Kurvs produkt-/variantregler.",
        "depends_on": ["mobile-offers", "product-identity"],
    },
    {
        "id": "offer-image-recognition",
        "name": "Offer Image Recognition",
        "layer": "iOS Intelligence",
        "kind": "client-engine",
        "runtime": "ios",
        "code": "ios/BaggerShopping/Services/OfferImageRecognitionService.swift",
        "description": "Klientside billedobservationer der kan hjælpe variantvalg og kræver bekræftelse.",
        "depends_on": ["product-identity"],
    },
    {
        "id": "geofence-engine",
        "name": "Store Geofence Engine",
        "layer": "iOS Automation",
        "kind": "client-engine",
        "runtime": "ios",
        "code": "ios/BaggerShopping/Services/GeofenceManager.swift",
        "description": "Butiksgeofences med reelt minimum 100 m og routing til indkøbslisten.",
        "depends_on": ["store-repository"],
    },
    {
        "id": "member-geofence-reminder",
        "name": "Member Price Geofence Reminder",
        "layer": "iOS Automation",
        "kind": "client-engine",
        "runtime": "ios",
        "code": "ios/BaggerShopping/Services/MemberPriceGeofenceReminder.swift",
        "description": "Lokale påmindelser om relevante medlemspriser ved butiksankomst.",
        "depends_on": ["geofence-engine", "member-pricing"],
    },
    {
        "id": "store-repository",
        "name": "Store Repository & Search",
        "layer": "iOS Automation",
        "kind": "client-engine",
        "runtime": "ios",
        "code": "ios/BaggerShopping/Services/StoreRepository.swift + StoreSearchService.swift",
        "description": "Butiksdata og lokal søgning som fodrer geofence-opsætningen.",
        "depends_on": [],
    },
    {
        "id": "performance-cache",
        "name": "iOS Performance Cache",
        "layer": "iOS Runtime",
        "kind": "client-infrastructure",
        "runtime": "ios",
        "code": "ios/BaggerShopping/Services/PerformanceCache.swift + ShoppingListPerformance.swift",
        "description": "Responsiv klientcache og performance-lag uden at ændre serverens autoritative data.",
        "depends_on": ["mobile-api"],
    },
)


DATAFLOW: tuple[dict[str, str], ...] = (
    {"from": "provider-tjek", "to": "flyer-adapters", "label": "kataloger · sider · hotspots"},
    {"from": "flyer-adapters", "to": "flyer-readiness", "label": "normaliseret source generation"},
    {"from": "flyer-readiness", "to": "luna-worker", "label": "ny/ændret avis"},
    {"from": "luna-worker", "to": "luna-semantic-audit", "label": "high-detail page audit"},
    {"from": "luna-semantic-audit", "to": "luna-semantic-guards", "label": "strukturerede facts"},
    {"from": "luna-semantic-guards", "to": "member-coverage", "label": "safe / needs crop"},
    {"from": "member-coverage", "to": "flyer-serving", "label": "verified enrichment"},
    {"from": "flyer-serving", "to": "mobile-offers", "label": "customer-safe tilbud"},
    {"from": "mobile-offers", "to": "smart-offer-matching", "label": "søgning · aviser · tilbud"},
    {"from": "smart-offer-matching", "to": "shopping-sync", "label": "valgt tilbud til listevare"},
    {"from": "shopping-sync", "to": "samsung-food", "label": "fælles liste sync"},
    {"from": "member-coverage", "to": "flyer-push-worker", "label": "quality gate"},
    {"from": "flyer-push-worker", "to": "apple-apns", "label": "Ny tilbudsavis"},
    {"from": "store-repository", "to": "geofence-engine", "label": "butikspositioner"},
    {"from": "geofence-engine", "to": "member-geofence-reminder", "label": "ankomst"},
)


IOS_RELEASE = {"version": "1.0.0", "build": "70"}


def catalog() -> list[dict[str, Any]]:
    return [dict(component) for component in COMPONENTS]


def dataflow() -> list[dict[str, str]]:
    return [dict(edge) for edge in DATAFLOW]
